In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt
import default_settings.set_plot_korean_char


plt.style.use('bmh')
%matplotlib inline

In [2]:
data_root = Path("C:/Users/Kaph/Desktop/Data/")
stock_items_path = data_root / "Stock Items"
financial_items_path = data_root / "Financial Statements"

In [3]:
ts_price = pd.read_csv(stock_items_path / "ts_adj_close_price.csv", parse_dates=["Date"], index_col="Date")
ts_capsize = pd.read_csv(stock_items_path / "ts_capsize.csv", parse_dates=["Date"], index_col="Date")

In [28]:
total_assets = pd.read_csv(financial_items_path / "자산총계.csv", index_col="Period").filter(regex='R$', axis='index').dropna(how='all', axis='index')
net_assets = pd.read_csv(financial_items_path / "자본총계.csv", index_col="Period").filter(regex='R$', axis='index').dropna(how='all', axis='index')
gross_profit = pd.read_csv(financial_items_path / "Gross Profit.csv", index_col="Period").filter(regex='R$', axis='index').dropna(how='all', axis='index')

In [49]:
def get_financial_data(*names: str, rolling_sum: bool=False, rolling_window: int=4):
    for name in names:
        data = pd.read_csv(financial_items_path / f"{name}.csv", index_col="Period")
        data = data.filter(regex='R$', axis='index')
        data.dropna(how='all', axis='index', inplace=True)
        if rolling_sum:
            data = data.rolling(rolling_window).sum()
        yield data

In [52]:
total_assets, net_assets, gross_profit = list(get_financial_data('자산총계', '자본총계', 'Gross Profit'))

In [54]:
total_assets

,신한은행,동화약품,우리은행,KR모터스,경방,메리츠화재,삼양홀딩스,삼양홀딩스우,하이트진로,하이트진로1우,...,SBI핀테크솔루션즈,엑세스바이오,잉글우드랩,코오롱티슈진,JTC,SNK,미투젠,소마젠,프레스티지바이오파마,네오이뮨텍
Period,,,,,,,,,,,,,,,,,,,,,
200203R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200206R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200209R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200212R,2.485334e+11,8.668528e+08,3.234959e+11,434487074.0,2.172533e+09,8.111209e+09,3.776155e+09,NaN,6.750391e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200303R,2.599505e+11,8.525740e+08,3.403850e+11,435268195.0,2.151599e+09,8.323245e+09,3.692021e+09,NaN,6.824191e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202106R,1.728873e+12,1.742718e+09,1.523201e+12,659262099.1,5.202864e+09,1.022267e+11,1.601664e+10,NaN,1.453389e+10,NaN,...,1.584684e+09,8.860026e+08,480785969.0,283973607.0,1.701662e+09,1.181122e+09,475312785.0,212522358.0,NaN,601253783.0
202109R,1.768406e+12,1.766029e+09,1.566086e+12,681132233.1,5.105859e+09,1.042208e+11,1.650351e+10,NaN,1.396487e+10,NaN,...,1.712495e+09,1.111407e+09,488539818.0,228013064.0,1.527086e+09,1.092907e+09,492245981.0,208416693.0,NaN,685333707.0
202112R,1.808166e+12,1.780026e+09,1.607753e+12,693695583.6,5.111762e+09,1.065505e+11,1.707053e+10,NaN,1.429814e+10,NaN,...,1.816792e+09,1.383232e+09,508003463.0,216573943.0,1.393538e+09,1.096923e+09,501617273.0,203171817.0,2.491424e+09,776716162.0
202203R,1.846073e+12,1.802726e+09,1.650040e+12,690966899.5,5.116046e+09,1.086096e+11,1.762994e+10,NaN,1.423555e+10,NaN,...,1.875522e+09,2.118336e+09,520845739.0,206268078.0,1.288005e+09,1.090844e+09,526001332.0,200607668.0,2.469279e+09,754348156.0
202206R,1.894820e+12,1.819558e+09,1.705350e+12,679121241.8,5.132385e+09,1.108141e+11,1.793432e+10,NaN,1.424751e+10,NaN,...,1.859637e+09,2.834321e+09,534050710.0,204620668.0,1.183786e+09,NaN,532686331.0,202111949.0,2.364926e+09,737668566.0